"""@Kaizuryu"""


NEKO_GIFS = [
'CgACAgQAAxkBAAMrYqsUnGR_WSKGqHlEZf7y6HkYERYAAssLAAIonphSDdalOsV7SvckBA',
'CgACAgQAAxkBAAMuYqsUveNqlzPijbjFjKu7s_XjxPkAAmwJAAIGErhQ91BF0LmjUI8kBA',
'CgACAgQAAxkBAAMxYqsVJ8fGYUxPk4bozwQSeLnHassAAkMKAAJ3hRBTZifAU99mVPUkBA',
'CgACAgQAAxkBAAM2YqsVP3YBS-CRdwP7Y7BldYqQpoUAAr0LAALXAvBQxI6NdeN-9KYkBA',
'CgACAgIAAxkBAAM5YqsVSzUoI2hfP7SWLaARgHoXoUIAArwDAAKsUoBJMtAiy5zsOHokBA',
'CgACAgQAAxkBAAM8YqsVWWn-2hu2dKIFjYADops8GkgAAkgKAALfd-lRRubt0w6DL2UkBA',
'CgACAgQAAxkBAAM_YqsVba1Fx_uYXshjrYRGnEDlBuwAAgIMAALUNQhQl85MfEwjEuQkBA',
'CgACAgQAAxkBAANCYqsVd4Bx8bSX7kNhsmVmf9ErrTMAAtwCAAKzSl1RNMbxHZVn1fYkBA',
'CgACAgQAAxkBAANFYqsVhbz-lNmztm3kQD-1KrEtMVUAApsJAAJKQ4FTrApv8b4mbyAkBA',
'CgACAgQAAxkBAANIYqsVkfblz6kTvx3xxa6hNakFAhAAAjsZAAIxGGQH7NG_RZRZcuQkBA',
'CgACAgQAAxkBAANLYqsVq_iEWP7UHujaYCc-XzcymFMAAhsDAAK8KqxQy2qoV0Sm9_EkBA',
'CgACAgQAAxkBAANMYqsVq94MQ8G-yegkbOomompFgEUAAioJAAKMUyhQI0qgXgVwDkokBA',
'CgACAgQAAxkBAANNYqsVqycytgiSFoGcrjCWfuS-31UAAkkCAAKVzZRSo328NRXOTtIkBA',
'CgACAgQAAxkBAANOYqsVq16uzEa6RbP1E-Ge4K3uBCgAAgkNAAJhFoBRqPScY1M8bKYkBA',
'CgACAgQAAxkBAANPYqsVq60g7E29o3V54JHXGL4jnpQAAv8KAAJMg7hT2oDYsq-FzJ4kBA',
'CgACAgIAAxkBAANQYqsVq0DediMlY1rpPZfuD1DiF-IAArwDAAKsUoBJMtAiy5zsOHokBA',
'CgACAgQAAxkBAANRYqsVq5mts75j64nk3roQPcfepJ0AAr0LAALXAvBQxI6NdeN-9KYkBA',
'CgACAgQAAxkBAANSYqsVq0liFvD8IxdTsPgCptgrieQAAisLAAI6y7BTbGoeRWS3ItgkBA',
'CgACAgQAAxkBAANTYqsVq9AMgXbGEf50Wu4uD6_JeM0AAhsKAAKbqOhTq0LaOEquUqEkBA',
'CgACAgIAAxkBAANUYqsVqzE4jN19KFXHzl9B_PGQX0oAAjQHAALcyRhKZbta5VIkDPkkBA'
]


NEKO_TEXT = [

     "@Arsshh, the Neko, Scratches you!",

     "Nya! {user1} is a Neko!",

     "My Heart Goes Meow😻",

     "Neko Neko Niii!"

     "{user1} nyaed {user2}"

   ]

CATTO_GIFS = [
'CgACAgQAAxkBAAMrYqsUnGR_WSKGqHlEZf7y6HkYERYAAssLAAIonphSDdalOsV7SvckBA',
'CgACAgQAAxkBAAMuYqsUveNqlzPijbjFjKu7s_XjxPkAAmwJAAIGErhQ91BF0LmjUI8kBA',
'CgACAgQAAxkBAAMxYqsVJ8fGYUxPk4bozwQSeLnHassAAkMKAAJ3hRBTZifAU99mVPUkBA',
'CgACAgQAAxkBAAM2YqsVP3YBS-CRdwP7Y7BldYqQpoUAAr0LAALXAvBQxI6NdeN-9KYkBA',
'CgACAgIAAxkBAAM5YqsVSzUoI2hfP7SWLaARgHoXoUIAArwDAAKsUoBJMtAiy5zsOHokBA',
'CgACAgQAAxkBAAM8YqsVWWn-2hu2dKIFjYADops8GkgAAkgKAALfd-lRRubt0w6DL2UkBA',
'CgACAgQAAxkBAAM_YqsVba1Fx_uYXshjrYRGnEDlBuwAAgIMAALUNQhQl85MfEwjEuQkBA',
'CgACAgQAAxkBAANCYqsVd4Bx8bSX7kNhsmVmf9ErrTMAAtwCAAKzSl1RNMbxHZVn1fYkBA',
'CgACAgQAAxkBAANFYqsVhbz-lNmztm3kQD-1KrEtMVUAApsJAAJKQ4FTrApv8b4mbyAkBA',
'CgACAgQAAxkBAANIYqsVkfblz6kTvx3xxa6hNakFAhAAAjsZAAIxGGQH7NG_RZRZcuQkBA',
'CgACAgQAAxkBAANLYqsVq_iEWP7UHujaYCc-XzcymFMAAhsDAAK8KqxQy2qoV0Sm9_EkBA',
'CgACAgQAAxkBAANMYqsVq94MQ8G-yegkbOomompFgEUAAioJAAKMUyhQI0qgXgVwDkokBA',
'CgACAgQAAxkBAANNYqsVqycytgiSFoGcrjCWfuS-31UAAkkCAAKVzZRSo328NRXOTtIkBA',
'CgACAgQAAxkBAANOYqsVq16uzEa6RbP1E-Ge4K3uBCgAAgkNAAJhFoBRqPScY1M8bKYkBA',
'CgACAgQAAxkBAANPYqsVq60g7E29o3V54JHXGL4jnpQAAv8KAAJMg7hT2oDYsq-FzJ4kBA',
'CgACAgIAAxkBAANQYqsVq0DediMlY1rpPZfuD1DiF-IAArwDAAKsUoBJMtAiy5zsOHokBA',
'CgACAgQAAxkBAANRYqsVq5mts75j64nk3roQPcfepJ0AAr0LAALXAvBQxI6NdeN-9KYkBA',
'CgACAgQAAxkBAANSYqsVq0liFvD8IxdTsPgCptgrieQAAisLAAI6y7BTbGoeRWS3ItgkBA',
'CgACAgQAAxkBAANTYqsVq9AMgXbGEf50Wu4uD6_JeM0AAhsKAAKbqOhTq0LaOEquUqEkBA',
'CgACAgIAAxkBAANUYqsVqzE4jN19KFXHzl9B_PGQX0oAAjQHAALcyRhKZbta5VIkDPkkBA'
]

CATTO_TEXT = [

      "Cat Is Sleeping Nya!",

      "Catto Just Scratched you",

      "@Arsshh is the Catto Lord",

      "Catto is playing with @Redeye_Ghoul now!",

      "Catto Loves You ❤"

    ]